# File structure version
version: '3.7'

services:
  
  postgres:
    restart: always
    shm_size: '512MB'
    image: yangricardo/elisdb:latest #postgres:latest 
    container_name: elisapp_postgres
    hostname: postgres
    expose:
      - 5432
    env_file:
      - ${PWD}/config/db/.env
    networks:
      - db
    volumes:
      - postgres:/data

  redis:
    restart: always
    container_name: elisapp_redis
    hostname: redis
    image: redis
    volumes:
      - redis:/data
    expose:
      - 6379
    networks: 
      - db

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    volumes:
      - redis-commander:/redis-commander
    expose:
      - 6379
    ports:
      - "8081:8081"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks: 
      - db

  app:
    restart: always
    build:
      context: ${PWD}
    container_name: elisapp_app
    image: yangricardo/elisapp:latest
    command : sh /config/on-container-start.sh
    hostname: app
    env_file:
      - ${PWD}/config/app/.env
    volumes:
      - ${PWD}/app:/app
      - ${HOME}/TJ_FILES:/tj_files
      - static:/srv/static
      - media:/srv/media
    expose:
      - 8000
    ports:
      - 8888:8888
      - 3500:3500
      - 9000:9000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      nginx:
          ipv4_address: 172.16.1.2
      db:
    depends_on:
      - postgres
      - redis

  # worker:
  #   build:
  #     context: .
  #   container_name: elisapp_celery
  #   image: yangricardo/elisapp:latest
  #   command: celery -A backend worker -E -l info
  #   volumes:
  #     - ./app:/app
  #   expose:
  #     - 5555
  #   depends_on:
  #     - app
  #     - redis
  #   networks: 
  #     - db

  # Web server based on official nginx image
  # Connect external 8000 (which you can access from browser)
  # with internal port 8000(which will be linked to app port 8000 in configs)
  # Connect local nginx configuration with image configuration
  nginx:
    image: nginx
    container_name: elisapp_nginx
    restart:  always
    hostname: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${PWD}/config/nginx:/etc/nginx/conf.d
      # - ./config/nginx/certbot/conf:/etc/letsencrypt
      # - ./config/nginx/certbot/www:/var/www/certbot
      - ${PWD}/config/nginx/elisapp.dev.crt:/etc/nginx/elisapp.dev.crt # New Line!
      - ${PWD}/config/nginx/elisapp.dev.key:/etc/nginx/elisapp.dev.key # New Line!
      - static:/srv/static:ro
      - media:/srv/media:ro
    depends_on:
      - app
    networks: 
      nginx:
        ipv4_address: 172.16.1.3
 
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./config/nginx/certbot/conf:/etc/letsencrypt
  #     - ./config/nginx/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  pgadmin:
    image: dpage/pgadmin4
    restart:  always
    hostname: pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
      - pgadmin:/pgadmin4/config_local.py
      - pgadmin:/pgadmin4/servers.json
      - pgadmin:/certs/server.cert
      - pgadmin:/certs/server.key
    environment:
      PGADMIN_DEFAULT_EMAIL: 'yangricardo17@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'elisdbpassword'
    ports:
      - 8001:80
    depends_on:
      - postgres
    networks: 
      - db

networks:
  nginx:
    external:
      name: elisapp_network
  db:
    driver: bridge

volumes:
  postgres:
  redis:
  redis-commander:
  pgadmin:
  static:
  media: