# File structure version
version: '3.7'

services:
  # Database based on official postgres image
  db:
    restart: always
    image: postgres
    container_name: elisapp_postgres
    hostname: db
    ports:
      - 15432:5432
    env_file:  # <-- we use the previously defined values
      - config/db/.env
    networks:  # <-- connect to the bridge
      - db_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis:
    restart: always
    container_name: elisapp_redis
    hostname: redis
    image: redis
    expose:
      - 6379
    networks: 
      - db_network

  rabbitmq:
    restart: always
    hostname: rabbitmq
    container_name: elisapp_rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=elisdbadmin
      - RABBITMQ_DEFAULT_PASS=elisdbpassword
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - db_network
    depends_on:
      - redis

  app:
    restart: always
    build:
      context: .
    container_name: elisapp_app
    image: yangricardo/elisapp:latest
    command: sh /config/on-container-start.sh
    hostname: app
    env_file:
      - config/app/.env
    volumes:
      - ./app:/app
      - /home/yang/TJ_FILES/:/tj_files
      - static:/srv/static
      - media:/srv/media
    expose:
      - 8000
    ports:
      - 8888:8888
      - 5678:5678
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - nginx_network
      # - nginx-proxy
      - db_network  # <-- connect to the bridge
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
    container_name: elisapp_celery
    image: yangricardo/elisapp:latest
    command: celery worker -A backend 
    volumes:
      - ./app:/app
    depends_on:
      - app
      - rabbitmq
    networks: 
      - db_network

  # Web server based on official nginx image
  # Connect external 8000 (which you can access from browser)
  # with internal port 8000(which will be linked to app port 8000 in configs)
  # Connect local nginx configuration with image configuration
  nginx:
    image: nginx
    container_name: elisapp_nginx
    restart:  always
    hostname: nginx
    ports:
      - 80:80
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/srv/static:ro
      - media:/srv/media:ro
    depends_on:
      - app
    networks: 
      - nginx_network
 
  pgadmin:
    image: dpage/pgadmin4
    restart:  always
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'yangricardo17@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'elisdbpassword'
    ports:
      - 8001:80
    depends_on:
      - db
    networks: 
      - db_network

networks:
  # nginx-proxy:
  #   external:
  #     name: "nginx-proxy"
  nginx_network:
    driver: bridge
  db_network:  # <-- add the bridge
    driver: bridge

volumes:
  db_volume:
  static:
  media: