# Generated by Django 2.1.7 on 2019-03-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
