# Generated by Django 2.2.1 on 2019-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvogadoDisponivel',
            fields=[
                ('oab', models.TextField(primary_key=True, serialize=False)),
                ('advogado', models.TextField()),
            ],
            options={
                'db_table': 'api_views_advogados_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdvogadoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(db_index=True)),
                ('oab', models.TextField(db_index=True)),
                ('polo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'api_mview_advogado_processo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnoDisponivel',
            fields=[
                ('ano', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_view_anos_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssuntoDisponivel',
            fields=[
                ('assunto', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_view_assuntos_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClasseDisponivel',
            fields=[
                ('classe', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_view_classes_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComarcasDisponivel',
            fields=[
                ('comarca', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_view_comarcas_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenciaDisponivel',
            fields=[
                ('competencia', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_view_competencias_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('cod_documento', models.TextField(primary_key=True, serialize=False)),
                ('id_tipo_documento', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_documento', models.CharField(max_length=210)),
            ],
            options={
                'db_table': 'api_mview_documento_processo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JuizDisponivel',
            fields=[
                ('matricula_juiz', models.TextField(primary_key=True, serialize=False)),
                ('juiz', models.TextField()),
                ('cargo_juiz', models.TextField()),
            ],
            options={
                'db_table': 'api_view_juizes_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonagemDisponivel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome_personagem', models.TextField()),
            ],
            options={
                'db_table': 'api_views_personagens_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonagemProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.TextField(db_index=True)),
                ('tipo_personagem', models.CharField(max_length=25)),
                ('participacao', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'api_mview_personagens_processo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessoEstatistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField()),
                ('referenciado', models.IntegerField()),
            ],
            options={
                'db_table': 'api_view_processo_estatistica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessoSimilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similaridade', models.FloatField()),
                ('processo_base_tj', models.IntegerField(db_index=True)),
                ('processo_base_cnj', models.IntegerField(blank=True, db_index=True, null=True)),
                ('processo_similar_tj', models.IntegerField(db_index=True)),
                ('processo_similar_cnj', models.IntegerField(blank=True, db_index=True, null=True)),
                ('processo_base_comarca', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('processo_similar_comarca', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('processo_base_serventia', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('processo_similar_serventia', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('processo_base_assunto', models.TextField()),
                ('processo_similar_assunto', models.TextField()),
                ('processo_base_classe', models.TextField()),
                ('processo_similar_classe', models.TextField()),
                ('processo_base_competencia', models.TextField()),
                ('processo_similar_competencia', models.TextField()),
            ],
            options={
                'db_table': 'api_mview_processossimilares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_sentenca', models.TextField()),
                ('ato_juiz', models.CharField(max_length=20)),
                ('nome_juiz', models.CharField(max_length=100)),
                ('matricula_juiz', models.TextField()),
                ('cargo_juiz', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_mview_sentencas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServentiaDisponivel',
            fields=[
                ('serventia', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_view_serventias_disponiveis',
                'managed': False,
            },
        ),
    ]
