# Generated by Django 2.2.1 on 2019-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo_tj', models.CharField(db_index=True, max_length=18)),
                ('processo_cnj', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('comarca', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('serventia', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('assunto', models.TextField(blank=True, null=True)),
                ('classe', models.TextField(blank=True, null=True)),
                ('competencia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_mview_sentencas',
                'managed': False,
            },
        ),
    ]
