# Generated by Django 2.2.2 on 2019-06-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personagemdisponivel',
            table='api_view_personagens_disponiveis',
        ),
    ]
