# Generated by Django 2.2.1 on 2019-06-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaosimilaridade',
            options={'managed': True},
        ),
    ]
