# Generated by Django 2.2.2 on 2019-06-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20190617_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseAssuntoDisponivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField()),
                ('classe', models.TextField()),
            ],
            options={
                'db_table': 'api_view_classes_assuntos_disponiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComarcaServentiaDisponivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serventia', models.TextField()),
                ('comarca', models.TextField()),
            ],
            options={
                'db_table': 'api_view_comarcas_serventias_disponiveis',
                'managed': False,
            },
        ),
    ]
