# Generated by Django 2.2.1 on 2019-06-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_processo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processo',
            table='api_mview_processo',
        ),
    ]
