# Generated by Django 2.2.2 on 2019-06-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_classeassuntodisponivel_comarcaserventiadisponivel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssuntoDisponivel',
        ),
        migrations.DeleteModel(
            name='ClasseDisponivel',
        ),
        migrations.DeleteModel(
            name='ComarcasDisponivel',
        ),
        migrations.DeleteModel(
            name='ServentiaDisponivel',
        ),
    ]
