# Generated by Django 2.2.1 on 2019-05-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processo', to='api.Processo', to_field='cod_proc'),
        ),
    ]
