# Generated by Django 2.2 on 2019-04-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='cod_pers_ativo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personagem_ativo', to='api.TipoPersonagem'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='cod_pers_passivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personagem_passivo', to='api.TipoPersonagem'),
        ),
    ]
