# Generated by Django 2.2 on 2019-04-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classeassunto',
            unique_together={('classe', 'assunto')},
        ),
    ]
