# Generated by Django 2.2 on 2019-05-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190502_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_cad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
