# Generated by Django 2.2.1 on 2019-05-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190518_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('cod_adv', models.IntegerField(primary_key=True, serialize=False)),
                ('num_oab', models.TextField(db_index=True)),
                ('nome_adv', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('cod_pers', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Personagem')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Processo', to_field='cod_proc')),
                ('tipo_personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoPersonagem')),
            ],
            options={
                'unique_together': {('processo', 'personagem')},
            },
        ),
        migrations.CreateModel(
            name='AdvogadoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_polo', models.CharField(blank=True, max_length=1, null=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advogado')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Processo', to_field='cod_proc')),
                ('tipo_personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoPersonagem')),
            ],
            options={
                'unique_together': {('processo', 'advogado')},
            },
        ),
    ]
