# Generated by Django 2.2 on 2019-04-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190407_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='desc_comp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencia',
            name='desc_res',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processo',
            name='competencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Competencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processo',
            name='cod_proc',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProcessoUnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cnj', models.CharField(max_length=25, unique=True)),
                ('id_proc', models.IntegerField(unique=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Processo')),
            ],
        ),
    ]
