# Generated by Django 2.2.1 on 2019-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190512_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentoprocesso',
            name='txt_descr_len',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='andamentoprocesso',
            unique_together={('processo', 'ordem', 'txt_descr_len')},
        ),
    ]
