# Generated by Django 2.2 on 2019-05-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processo_data_cad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together=set(),
        ),
    ]
