# Generated by Django 2.2 on 2019-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190422_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comarca',
            name='desc_coma',
            field=models.CharField(max_length=50),
        ),
    ]
