# Generated by Django 2.2 on 2019-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190425_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_carg', models.IntegerField(primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=50)),
            ],
        ),
    ]
