# Generated by Django 2.2 on 2019-04-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190423_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serventia',
            name='desc_redu',
        ),
        migrations.AlterField(
            model_name='serventia',
            name='desc_abre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serventia',
            name='desc_serv',
            field=models.CharField(max_length=80),
        ),
    ]
