# Generated by Django 2.2 on 2019-04-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('num_matr', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cod_carg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Cargo')),
            ],
        ),
    ]
