# Generated by Django 2.2.1 on 2019-05-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190520_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('cod_docto_elet', models.TextField(primary_key=True, serialize=False)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Assunto')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Classe')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Competencia')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Processo', to_field='cod_proc')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoDocumento')),
            ],
        ),
    ]
