# Generated by Django 2.2 on 2019-04-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190423_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='desc_res',
            field=models.CharField(max_length=15),
        ),
    ]
