# Generated by Django 2.2.1 on 2019-05-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documentoprocesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessosSimilares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similaridade', models.FloatField()),
                ('processo_base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processo_base', to='api.Processo', to_field='cod_proc')),
                ('processo_similar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processo_similar', to='api.Processo', to_field='cod_proc')),
            ],
        ),
    ]
