# Generated by Django 2.2 on 2019-05-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tipodecisaorecurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtoJuiz',
            fields=[
                ('cod_tip_ato', models.IntegerField(primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AtoJuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ato', models.IntegerField()),
                ('descr', models.CharField(max_length=60)),
                ('tipo_ato_juiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoAtoJuiz')),
                ('tipo_movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoMovimento')),
            ],
            options={
                'unique_together': {('cod_ato', 'tipo_ato_juiz', 'tipo_movimento')},
            },
        ),
    ]
