# Generated by Django 2.2 on 2019-05-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_atojuiz_tipoatojuiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tip_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=210)),
            ],
        ),
    ]
