# Generated by Django 2.2.1 on 2019-05-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_processossimilares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogadoprocesso',
            name='advogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advogado_processo', to='api.Advogado'),
        ),
        migrations.AlterField(
            model_name='advogadoprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processo_advogado', to='api.Processo', to_field='cod_proc'),
        ),
        migrations.AlterField(
            model_name='advogadoprocesso',
            name='tipo_personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_personagem_advogado_processo', to='api.TipoPersonagem'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='ato_juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ato_juiz_andamento_processo', to='api.AtoJuiz'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='juiz_andamento_processo', to='api.Funcionario'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processo_andamento', to='api.Processo', to_field='cod_proc'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='serventia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='serventia_andamento_processo', to='api.Serventia'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='tipo_andamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_andamento_processo', to='api.TipoAndamento'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='tipo_ato_juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_ato_juiz_andamento_processo', to='api.TipoAtoJuiz'),
        ),
        migrations.AlterField(
            model_name='andamentoprocesso',
            name='tipo_decisao_recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_decisao_recurso', to='api.TipoDecisaoRecurso'),
        ),
        migrations.AlterField(
            model_name='atojuiz',
            name='tipo_ato_juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_ato_juiz', to='api.TipoAtoJuiz'),
        ),
        migrations.AlterField(
            model_name='atojuiz',
            name='tipo_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_movimento_ato_juiz', to='api.TipoMovimento'),
        ),
        migrations.AlterField(
            model_name='classeassunto',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assunto_classe', to='api.Assunto'),
        ),
        migrations.AlterField(
            model_name='classeassunto',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_assunto', to='api.Classe'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_assunto', to='api.Assunto'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_classe', to='api.Classe'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_competencia', to='api.Competencia'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_processo', to='api.Processo', to_field='cod_proc'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cod_carg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cargo', to='api.Cargo'),
        ),
        migrations.AlterField(
            model_name='personagemprocesso',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personagem_processo', to='api.Personagem'),
        ),
        migrations.AlterField(
            model_name='personagemprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processo_personagem', to='api.Processo', to_field='cod_proc'),
        ),
        migrations.AlterField(
            model_name='personagemprocesso',
            name='tipo_personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_personagem_processo', to='api.TipoPersonagem'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assunto_processo', to='api.Assunto'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='competencia_processo', to='api.Competencia'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='serventia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='serventia_processo', to='api.Serventia'),
        ),
        migrations.AlterField(
            model_name='serventia',
            name='comarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comarca', to='api.Comarca'),
        ),
        migrations.AlterField(
            model_name='tipoandamento',
            name='cod_tip_mov',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_movimento_andamento', to='api.TipoMovimento'),
        ),
        migrations.AlterField(
            model_name='tipomovimento',
            name='cod_tip_mov_pai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_movimento_pai', to='api.TipoMovimento'),
        ),
        migrations.AlterField(
            model_name='tipopersonagem',
            name='cod_tip_pers_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_personagem_inverso', to='api.TipoPersonagem'),
        ),
    ]
