# Generated by Django 2.2 on 2019-04-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190423_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assunto',
            name='cod_tip_assunto',
        ),
    ]
