# Generated by Django 2.2.1 on 2019-05-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190526_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_processo', to='api.Classe'),
        ),
    ]
